#!/bin/bash
SELF="$(readlink -f "$0")"
HERE="$(dirname "$SELF")"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export PATH="${HERE}/usr/bin:${PATH}"
exec "${HERE}/opt/iPhotron/main.bin" "$@"
